export const PALAVRAS_CHAVE_EVENTOS: string[] = [
    'evento',
    'show',
    'festa',
    'festival',
    'teatro',
    'cinema',
    'musical',
    'concerto',
    'exposição',
    'espetáculo',
    'campeonato',
    'competição',
    'seminário',
    'workshop',
    'palestra',
    'conferência',
    'congresso',
    'curso',
    'oficina',
    'roda de conversa',
    'sarau',
    'feira',
    'bazar',
    'inauguração',
    'live',
    'lançamento',
    'encontro',
    'jornada',
    'caravana',
    'mutirão',
    'balada',
    'matinê',
    'aniversário',
    'baile',
    'retiro',
    'imersão',
    'vernissage',
    'sessão',
    'trilha',
    'caminhada',
    'gincana',
    'celebração',
    'homenagem',
    'missa',
    'procissão',
    'espetáculo infantil',
    'teatro de rua',
    'apresentação',
    'programação cultural',
    'atividades recreativas'
  ];
  